### ISSUE TITLE
How to define "BIGINT UNSIGNED"  field?

### ISSUE THREAD

**Issue by odk211** [gumi/yacto#1]
First, thank you for this awesome library! 
It's really helpful for us! 😄 

I found I can define "BIGINT UNSIGNED"  field to write schema as below.

```elixir
schema @auto_source do
  field :user_id, :integer, meta: [null: false, type: :"'bigint(20) unsigned'"]
end
```

The single quote  `'` in the `type` option is important.

But this is a little bit technical way.
 Is there any better way ?

Thanks,

**Comment by melpon** [comment]
It is fixed by https://github.com/gumi/yacto/commit/2cb843be90f995df8cee15c13a510e8dcf8c9a03
You can write `:"bigint(20) unsigned"` with this commit.
Please use yacto 1.0.6 or greater. 
Thank you for your reporting!

**Comment by odk211** [comment]
I checked it works !! 
Thank you for blazing fast reply and fix!! 😂
