### ISSUE TITLE
When delete both the field and index, should delete index first

### ISSUE THREAD

**Issue by h1u2i3** [gumi/yacto#12]
Sometimes when we trying to remove a field which has index added, it will generate the migrations like: 

```elixir
  def change(Qas.Taozui.Migration.Coupon) do
    alter table("coupons") do
      remove(:status)
      remove(:user_id)
    end
    drop index("coupons", [:user_id], [name: :coupons_user_id])
    create index("coupons", [:unique_number], [name: :coupons_unique_number])
  end
```
These operations should failed when do migrations(we should delete the inde first).
I have done a fix for this issue in #11 

Thank you for this wonderful tool.

**Comment by melpon** [comment]
Merged. Thank you!
