### ISSUE TITLE
(CompileError) config/config.exs:1: module Config is not loaded and could not be found

### ISSUE THREAD

**Issue by mori5321** [gumi/yacto#16]
I tried to contribute to this module.

However, when I try to run 'mix test',  an error raised.

```
$ mix test
** (CompileError) config/config.exs:1: module Config is not loaded and could not be found
    (elixir) lib/code.ex:232: Code.eval_string/3
    (mix) lib/mix/config.ex:220: Mix.Config.eval!/2
```

Any files or modules are needed to run test?  I would be glad if someone helps me.

**Comment by hiromoon** [comment]
Which Elixir and yacto version, do you use?

**Comment by melpon** [comment]
これは Elixir 1.8 以下でビルドしたためだと思うので close します。
