### ISSUE TITLE
How to rollback single transaction?

### ISSUE THREAD

**Issue by odk211** [gumi/yacto#2]
Hello 😃 
[Ecto.Repo.rollback/1](https://hexdocs.pm/ecto/Ecto.Repo.html#c:rollback/1) returns `{:error, value}`. 
But it seems not match to `{:error, value}` at single repo `Yacto.XA.transaction/3` .
https://github.com/gumi/yacto/blob/master/lib/yacto/xa.ex#L163

Can I use `Ecto.Repo.rollback` with yacto?
Or is there any better way other than `Ecto.Repo.rollback` ?
Thanks,

**Comment by melpon** [comment]
I'm thinking of providing `Yacto.rollback/1`.
In single transaction, call `Ecto.Repo.rollback/1` and then raise `RollbackError`. In XA transaction, send `XA ROLLBACK` query and then raise `RollbackError`.

**Comment by melpon** [comment]
Implement `Yacto.XA.rollback/2` on yacto-1.2.0. You can use it now.

**Comment by odk211** [comment]
Thanks a lot ! 😆 It will help us!
