### ISSUE TITLE
マイグレーション対象のDBを指定したい

### ISSUE THREAD

**Issue by odk211** [gumi/yacto#21]
repo の指定がない場合、 `Yacto.DB.all_repos()` に対して マイグレーションをしていますが、all_repos には ReadOnly でマイグレーションを実行したくない レポジトリも含んでおり、なにかしらマイグレーションを実行しない database を指定する方法が欲しいです。
ecto は create や drop 対象を `Application.fetch_env!(:my_app, :ecto_repos)` で指定する事ができるので、デフォルトで `ecto_repos` を見るようにするのはどうでしょうか？

今まで特に困ってなかったのですが、ローカル環境で ReadWriteのDBとReadOnlyのDBに同じDBを指定しており、 `mix yacto.migrate --fake` すると ReadOnly DBのマイグレーション(yacto_schema_migrations の drop, create のみ)が後に実行されるため、 yacto_schema_migrations のレコードが空になってしまう。という事が起きました。

(ローカル環境では `mix yacto.migrate --fake` ではなく、 reset をすれば良いし、repo指定すれば良いので、困ってはないです。)

**Comment by melpon** [comment]
あーなるほど、`:ecto_repos` は全部の DB 一覧を指定する訳じゃないんですね。デフォルトで `:ecto_repos` を見るのでいい気がするので直します。

（あと、config 上では別の DB のものを同一の DB として指すようにするのは Ecto 的にダメみたいなのをどこかで見た気がするんですが、これはもしかしたら勘違いだったかもしれないです。）

**Comment by odk211** [comment]
そうですね。 `:ecto_repos` では ReadWriteのDBのみ指定するようにしています。ありがとうございます！

**Comment by melpon** [comment]
`:ecto_repos` を見るように修正しました。2.0.0-rc.1 でリリース済みです。
（同一の DB を指すのは、以前読んだのを再度読み返したら特に問題無さそうな感じでした。2PC とかその辺の話でした）

**Comment by odk211** [comment]
対応ありがとうございました！こちらでも確認しましたが問題なさそうです！
